// <auto-generated />
using IpWatcher.Infrastructure.Storage.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpWatcher.Infrastructure.Storage.EfCore.Migrations
{
    [DbContext(typeof(IpWatcherDbContext))]
    [Migration("20251226193655_AddLogEventsTable")]
    partial class AddLogEventsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("IpWatcher.Infrastructure.Storage.EfCore.IpHistoryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedUtc")
                        .HasDatabaseName("IX_IpHistory_ChangedUtc");

                    b.ToTable("IpHistory", (string)null);
                });

            modelBuilder.Entity("IpWatcher.Infrastructure.Storage.EfCore.LogEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogEventJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimestampUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_LogEvents_Level");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_LogEvents_TimestampUtc");

                    b.ToTable("LogEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
