// <auto-generated />
using IpWatcher.Infrastructure.Storage.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpWatcher.Infrastructure.Storage.EfCore.Migrations
{
    [DbContext(typeof(IpWatcherDbContext))]
    partial class IpWatcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("IpWatcher.Infrastructure.Storage.EfCore.IpHistoryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedUtc")
                        .HasDatabaseName("IX_IpHistory_ChangedUtc");

                    b.ToTable("IpHistory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
